### ISSUE TITLE
Access to Datasets (unpublished, non-existent, and more)

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#671]
There are a number of smaller issues/comments from code review that fall under how datasets are accessed: 

- [x] Downloading a non-existent dataset and getting a 500 error instead of a 404 error. To fix this, a related query that fetches datasets needs to return an option instead of an actual dataset. More notes [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1301629912).
- [x] Change download path to `/projects/:projectId/datasets/:name/entities.csv` Comment [here](https://github.com/getodk/central-backend/pull/576#discussion_r1012103011).
- [x] Dataset CSV streaming endpoints return data even if dataset is not yet published. See notes [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1309046061).
- [x] You can link a form attachment to a dataset that is not yet published. See notes [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1309055161).
- [x] Dataset property included in CSV download even if form for that dataset is not yet published. Note [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1309167680). This might be addressed by issue #666  that involves adding `publishedAt` to dataset properties.
