### ISSUE TITLE
Update code to reflect latest Entity Spec

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#676]
The xform spec has been updated since the current version of the code. Some of the changes are as follows: 

### Structure:
- [x] Reject form definitions written for future spec versions and only allow ones that start with `2022.1`. More notes [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1310825614).
- [x] The entity system properties (`dataset`, `id`, and `create`) are expected to be found in the attributes of the entity node and and `label` is its own child node.
- [x] Not worrying (much) about entity namespace for now. Tracked at [#680](https://github.com/getodk/central-backend/issues/680).

### Validation:
- [x] ~Property name validation: we already reject `name` and `label` properties but also need to reject names starting with `__`. Maybe want to reject strange characters, too.~ **Now tracked at [#688](https://github.com/getodk/central-backend/issues/688).**
- [x] Dataset name validation: make it case **sensitive** (currently case-insensitive). Notes [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1302139099).
- [x] Dataset name validation: make sure to trim whitespace. Notes [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1301693117).
- [x] ~Maybe disallow `itemsets` as dataset name??~ [#673](https://github.com/getodk/central-backend/issues/673)
- [x] Lowercase the entity uuid (or maybe make it case-insensitive in the database?). Notes [here](https://github.com/getodk/central-backend/pull/576#discussion_r1015861945).
- [x] Only create entity if `create` is `1` or `true`
