### ISSUE TITLE
Update API Docs for 2023.1

### ISSUE THREAD

**Issue by ktuite** [getodk/central-backend#733]
This issue tracks parts of the backend API docs we need to update for the 2023.1 release:

- [ ] Dataset metadata (linked forms) added in PR #731 
- [ ] Extended metadata on Datasets (entity count and last entity timestamp) added in PR #730
- [ ] `$select` can be used with complex types other than `__system`: #717
- [ ] Maybe add a note about the breaking change mentioned here: #724
